package com.yuxie.smsbomb.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.yuxie.smsbomb.bean.SmsApi;

import com.yuxie.smsbomb.greendao.SmsApiDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig smsApiDaoConfig;

    private final SmsApiDao smsApiDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        smsApiDaoConfig = daoConfigMap.get(SmsApiDao.class).clone();
        smsApiDaoConfig.initIdentityScope(type);

        smsApiDao = new SmsApiDao(smsApiDaoConfig, this);

        registerDao(SmsApi.class, smsApiDao);
    }
    
    public void clear() {
        smsApiDaoConfig.clearIdentityScope();
    }

    public SmsApiDao getSmsApiDao() {
        return smsApiDao;
    }

}
